# fly.toml app configuration file generated for facturacionres on 2023-10-08T23:42:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "facturacionres"
primary_region = "scl"

[build]
[env]
DB_PORT =  3306
DB_HOST =    "database-facturacion.czonvdkvudeb.us-east-2.rds.amazonaws.com"
DB_USER =  "engineersoft"
DB_PASS = "adminengineer"
DB_DATABASE =   "facturacion"   

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
