# fly.toml app configuration file generated for facturacionres on 2023-10-11T20:38:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "facturacionres"
primary_region = "scl"

[build]

[env]
  DB_DATABASE = "facturacion"
  DB_HOST = "database-facturacion.czonvdkvudeb.us-east-2.rds.amazonaws.com"
  DB_PASS = "adminengineer"
  DB_PORT = "3306"
  DB_USER = "engineersoft"
  TZ = "America/Bogota"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
